---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'set-version.yml'


stages:
  - lint
  - bump-version
  - build


variables:
  LINTING_ENABLED: true


.lint-job:
  stage: lint
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
  image: python:3.12-alpine
  before_script:
    - mkdir -p "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install .[lint]
  cache:
    paths:
      - '$APK_CACHE_DIR'
      - '$PIP_CACHE_DIR'
  rules:
    - if: $LINTING_ENABLED == 'true'


Ruff:
  extends: .lint-job
  script: ruff check saltbox_keycloak_init


Mypy:
  extends: .lint-job
  script: mypy saltbox_keycloak_init


Bump Keycloak Init version:
  stage: bump-version
  extends: .set-backend-version
  variables:
    INNER_VERSION_FILE: 'saltbox_keycloak_init/__init__.py'


Build Keycloak Init image:
  extends: .build-image
  stage: build
  variables:
    DOCKERFILE: 'Dockerfile'
    TARGET: keycloak-init
