---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'

  - project: 'saltbox/ci-lib'
    file: 'set-version.yml'


stages:
  - lint
  - bump-version
  - build


variables:
  LINTING_ENABLED: true


.lint-job:
  stage: lint
  variables:
    APK_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/apk/'
    UV_CACHE_DIR: '${CI_PROJECT_DIR}.cache/uv/'
    PROJ_PATH: 'saltbox_keycloak_init'
  image: python:3.12-alpine
  before_script:
    - mkdir -p "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" uv
    - uv sync --group=dev
  cache:
    paths:
      - '$APK_CACHE_DIR'
      - '$UV_CACHE_DIR'
  rules:
    - if: $LINTING_ENABLED == 'true'


Ruff:
  extends: .lint-job
  script: 'uv run ruff check "$PROJ_PATH"'


Mypy:
  extends: .lint-job
  script: 'uv run mypy "$PROJ_PATH"'


Bump Keycloak Init version:
  stage: bump-version
  extends: .set-backend-version
  variables:
    INNER_VERSION_FILE: 'saltbox_keycloak_init/__init__.py'


Build Keycloak Init image:
  extends: .build-image
  stage: build
  variables:
    DOCKERFILE: 'Dockerfile'
    TARGET: keycloak-init
