[project]
dynamic = ["version"]
name = "saltbox-keycloak-init"
requires-python = ">=3.12"
license = { file = 'LICENSE.txt' }
description = ""
readme = "README.md"
dependencies = [
    "setuptools==82.0.1",
    "setuptools-scm==10.0.5",
    "python-keycloak==7.1.1",
    "pydantic==2.12.5",
    "pydantic-settings==2.13.1",
]

[project.scripts]
saltbox-keycloak-init = 'saltbox_keycloak_init.main:main'

[project.urls]
Homepage = "https://saltbox.pro"
Documentation = "https://saltbox.pro"
Repository = "https://dev.saltbox.pro/saltbox/saltbox-keycloak-init"

[build-system]
requires = ["setuptools>=75.1.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["saltbox_keycloak_init*"]

[tool.setuptools.dynamic]
version = { attr = "saltbox_keycloak_init.__version__" }

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.ruff]
target-version = "py312"
line-length = 120
src = ["saltbox_keycloak_init", "tests"]
extend-exclude = ["docs", "env", "__pycache__", "*.egg", "htmlcov"]
respect-gitignore = true
unsafe-fixes = false

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
preview = true
select = [
    "B",     # flake8-bugbear
    "C90",   # mccabe
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
    "EM",    # flake8-errmsg
    "UP",    # pyupgrade
    "FA",    # flake8-future-annotations
    "LOG",   # flake8-logging
    "PTH",   # flake8-use-pathlib
    "ASYNC", # flake8-async
    "G",     # flake8-logging-format
    "E",     # pycodestyle errors
    "F",     # pyflakes
    "I",     # isort
    "S",     # flake8-bandit
    "W",     # pycodestyle warnings
    "N",     # pep8-naming
    "RUF",   # ruff checks
    "TD",    # flake8-todo
]
ignore = [
    # "E402",   # module level import not at top of file
    "E701",   # Multiple statements on one line (colon)
    "E722",   # do not use bare except
    "ERA",    # do not autoremove commented out code
    "N818",   # error-suffix-on-exception-name
    "RUF029", # declared `async`, but doesn't `await`: is usual for async framework
    "RUF036", # none-not-at-end-of-union
    "S404",   # `subprocess` module is possibly insecure
    "TD001",  # Invalid TODO tag
    "TD002",  # Author name in TODO
    "TD003",  # Found TODO in code
    "TD004",  # Missing colon in TODO
    "UP017",  # Use datetime.UTC alias (not available for 3.10)
    "UP040",  # type instead of TypeAlias PEP 695"
]
fixable = ["ALL"]
unfixable = [
    "F401", # Unused import
    "F841", # Unused variable
    "UP035", # Deprecated import
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "single"
inline-quotes = "single"
multiline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
check_untyped_defs = true
plugins = ["pydantic.mypy"]
python_version = "3.12"
ignore_missing_imports = false
color_output = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["venv/", ".venv/", "tests/*"]
strict = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
show_error_codes = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "if TYPE_CHECKING:",
    "pragma: no cover",
    "if __name__ == '__main__':",
]
