SALTBOX_CLIENT_CONFIG: dict[str, object] = {
    'rootUrl': '',
    'adminUrl': '',
    'baseUrl': '',
    'surrogateAuthRequired': False,
    'enabled': True,
    'alwaysDisplayInConsole': False,
    'clientAuthenticatorType': 'client-secret',
    'redirectUris': ['*'],
    'webOrigins': ['*'],
    'notBefore': 0,
    'bearerOnly': False,
    'consentRequired': False,
    'standardFlowEnabled': True,
    'implicitFlowEnabled': False,
    'directAccessGrantsEnabled': False,
    'serviceAccountsEnabled': False,
    'publicClient': False,
    'frontchannelLogout': True,
    'protocol': 'openid-connect',
    'attributes': {
        'oidc.ciba.grant.enabled': 'false',
        'backchannel.logout.session.required': 'true',
        'display.on.consent.screen': 'false',
        'oauth2.device.authorization.grant.enabled': 'false',
        'backchannel.logout.revoke.offline.tokens': 'false',
    },
    'authenticationFlowBindingOverrides': {},
    'fullScopeAllowed': True,
    'nodeReRegistrationTimeout': -1,
    'defaultClientScopes': ['acr', 'basic', 'email', 'profile', 'roles', 'web-origins'],
    'optionalClientScopes': ['address', 'microprofile-jwt', 'offline_access', 'phone'],
}

GRAFANA_CLIENT_CONFIG: dict[str, object] = {
    'rootUrl': '',
    'adminUrl': '',
    'baseUrl': '',
    'surrogateAuthRequired': False,
    'enabled': True,
    'alwaysDisplayInConsole': False,
    'clientAuthenticatorType': 'client-secret',
    'redirectUris': ['*'],
    'webOrigins': ['*'],
    'notBefore': 0,
    'bearerOnly': False,
    'consentRequired': False,
    'standardFlowEnabled': True,
    'implicitFlowEnabled': False,
    'directAccessGrantsEnabled': True,
    'serviceAccountsEnabled': False,
    'publicClient': False,
    'frontchannelLogout': True,
    'protocol': 'openid-connect',
    'attributes': {
        'oidc.ciba.grant.enabled': 'false',
        'backchannel.logout.session.required': 'true',
        'display.on.consent.screen': 'false',
        'oauth2.device.authorization.grant.enabled': 'true',
        'backchannel.logout.revoke.offline.tokens': 'false',
    },
    'protocolMappers': [
        {
            'name': 'client roles',
            'protocol': 'openid-connect',
            'protocolMapper': 'oidc-usermodel-client-role-mapper',
            'consentRequired': False,
            'config': {
                'multivalued': 'true',
                'user.client.role': 'grafana',
                'claim.name': 'resource_access.grafana.roles',
                'jsonType.label': 'String',
                'access.token.claim': 'true',
                'id.token.claim': 'true',
                'userinfo.token.claim': 'true',
            },
        },
        {
            'name': 'realm roles',
            'protocol': 'openid-connect',
            'protocolMapper': 'oidc-usermodel-realm-role-mapper',
            'consentRequired': False,
            'config': {
                'multivalued': 'true',
                'claim.name': 'realm_access.roles',
                'jsonType.label': 'String',
                'access.token.claim': 'true',
                'id.token.claim': 'true',
                'userinfo.token.claim': 'true',
            },
        },
    ],
    'authenticationFlowBindingOverrides': {},
    'fullScopeAllowed': True,
    'nodeReRegistrationTimeout': -1,
    'defaultClientScopes': ['acr', 'basic', 'email', 'profile', 'roles', 'web-origins'],
    'optionalClientScopes': ['offline_access'],
}
