name: CI


on:
  pull_request


env:
  PROJ_PATH: 'saltbox_keycloak_init'


jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: '3.12'
      - run: uv sync --group=dev
      - run: uv run ruff check ${PROJ_PATH}


  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: '3.12'
      - run: uv sync --group=dev
      - run: uv run mypy ${PROJ_PATH}
